function flagCdn(nationality) {
    const countryCodes = {
        "Afghan": "AF",
        "Albanian": "AL",
        "Algerian": "DZ",
        "American": "US",
        "American Samoan": "AS",
        "Andorran": "AD",
        "Angolan": "AO",
        "Anguillan": "AI",
        "Antiguans/Barbudans": "AG",
        "Argentinean": "AR",
        "Armenian": "AM",
        "Australian": "AU",
        "Austrian": "AT",
        "Azerbaijani": "AZ",
        "Bahamian": "AX",
        "Bahraini": "BH",
        "Baker Island": "BH",
        "Bangladeshi": "BD",
        "Barbadian": "BB",
        "batswana": "BW",
        "Belarusian": "BY",
        "Belgian": "BE",
        "Belizean": "BZ",
        "Beninese": "BJ",
        "Bermudian": "BM",
        "Bhutanese": "BT",
        "Bolivian": "BT",
        "Bosnian / Herzegovinian": "BA",
        "Brazilian": "BR",
        "British (Manx)": "IM",
        "British": "GB",
        "Bruneian": "BN",
        "Bulgarian": "BG",
        "Burkinabe": "BF",
        "Burundian": "BI",
        "Cambodian": "KH",
        "Cameroonian": "CM",
        "Canadian": "CA",
        "Cape Verdean": "CA",
        "Cayman Islands": "CA",
        "Central African": "KY",
        "Chadian": "TD",
        "Chilean": "CL",
        "Chinese (Hong Kong)": "HK",
        "Chinese": "CN",
        "Christmas Island (Indian Ocean)": "CX",
        "Cocos (Keeling) Islands": "CX",
        "Colombian": "CO",
        "Comoran": "CO",
        "Congolese": "KM",
        "Cook Islands": "CG",
        "Costa Rican": "CR",
        "Croatian": "HR",
        "Cuban": "CU",
        "Cypriot": "CY",
        "Czech": "CY",
        "Danish": "DK",
        "Djibouti": "DJ",
        "Dominican": "DM",
        "Dutch": "NL",
        "Ecuadorean": "EC",
        "Egyptian": "EG",
        "Emirati": "UA",
        "Equatorial Guinean": "GQ",
        "Eritrean": "ER",
        "Estonian": "EE",
        "Ethiopian": "ET",
        "Faroese": "FK",
        "Fijian": "FJ",
        "Filipino": "PE",
        "Finnish": "FI",
        "French": "FR",
        "French Guianese": "GF",
        "French Polynesian": "PF",
        "Gabonese": "GA",
        "Gambian": "GA",
        "Georgian": "GE",
        "German": "DE",
        "Ghanaian": "GH",
        "Greek": "GR",
        "Greenlandic": "GL",
        "Grenadian": "GD",
        "Guadeloupian": "GP",
        "Guamanian": "GU",
        "Guatemalan": "GT",
        "Guinea-Bissauan": "GW",
        "Guinean": "GN",
        "Guyanese": "GY",
        "Haitian": "HT",
        "Honduran": "HN",
        "Howland Island": "HK",
        "Hungarian": "HU",
        "I-Kiribati": "HU",
        "Icelander": "IS",
        "Indian": "IN",
        "Indonesian": "ID",
        "Iranian": "ID",
        "Iraqi": "IQ",
        "Irish": "IE",
        "Israeli": "IL",
        "Italian": "IT",
        "Ivorian": "CR",
        "Jamaican": "JM",
        "Japanese": "JP",
        "Jarvis Island": "JP",
        "Johnston Atoll (U.S.)": "JE",
        "Jordanian": "JO",
        "Kazakhstani": "KZ",
        "Kenyan": "KE",
        "Kingman Reef": "KE",
        "Kittian and Nevisian": "KN",
        "Kuwaiti": "KW",
        "Kyrgyz": "KG",
        "Laotian": "KG",
        "Latvian": "LV",
        "Lebanese": "LB",
        "Liberian": "LR",
        "Libyan": "LY",
        "Liechtensteiner": "LI",
        "Lithuanian": "LT",
        "Luxembourger": "LU",
        "Macaense": "MO",
        "Macedonian": "MO",
        "Mahoran": "YT",
        "Malagasy": "MG",
        "Malawian": "MW",
        "Malaysian": "MY",
        "Maldivan": "MV",
        "Malian": "ML",
        "Maltese": "MT",
        "Marshallese": "MT",
        "Martiniquais": "MQ",
        "Mauritanian": "MR",
        "Mauritian": "MU",
        "Mexican": "MX",
        "Micronesian": "MX",
        "Midway Islands (U.S.)": "FM",
        "Moldovan": "FM",
        "Monacan": "MC",
        "Mongolian": "MN",
        "Montenegrin": "ME",
        "Montserratian": "MS",
        "Moroccan": "MA",
        "Mosotho": "LS",
        "Mozambican": "MZ",
        "Myanmar": "MM",
        "Namibian": "NA",
        "Nauruan": "NR",
        "Navassa Island": "NR",
        "Nepalese": "NP",
        "New Caledonian": "NC",
        "New Zealander": "NZ",
        "Ni-Vanuatu": "NZ",
        "Nicaraguan": "NI",
        "Nigerian": "NG",
        "Nigerien": "NI",
        "Niuean": "NU",
        "Norfolk Island": "NF",
        "North Korean": "KI",
        "Northern Mariana Islands": "NF",
        "Norwegian": "NO",
        "Omani": "OM",
        "Pakistani": "PK",
        "Palauan": "PW",
        "Palestine": "PS",
        "Palmyra Atoll": "PS",
        "Panamanian": "PA",
        "Papua New Guinean": "PG",
        "Paraguayan": "PY",
        "Peruvian": "PE",
        "Pitcairn": "PN",
        "Polish": "PL",
        "Portuguese": "PT",
        "Puerto Rican": "PR",
        "Qatari": "QA",
        "Reunionese": "MK",
        "Romanian": "RO",
        "Russian": "RO",
        "Rwandan": "RW",
        "Saint Helena": "BL",
        "Saint Lucian": "LC",
        "Saint Pierre and Miquelon": "PM",
        "Saint Vincent and the Grenadines": "VC",
        "Salvadoran": "SV",
        "Samoan": "WS",
        "San Marinese": "SM",
        "Sao Tomean": "ST",
        "Saudi": "SA",
        "Senegalese": "SN",
        "Serbian": "RS",
        "Seychellois": "SC",
        "Sierra Leonean": "SL",
        "Singaporean": "SG",
        "Slovakian": "SK",
        "Slovenian": "SI",
        "Solomon Islander": "SB",
        "Somali": "SO",
        "South African": "ZA",
        "South Korean": "KI",
        "Spanish": "ES",
        "Sri Lankan": "LK",
        "Sudanese": "LK",
        "Surinamer": "SR",
        "Svalbard and Jan Mayen": "SJ",
        "Swazi": "SJ",
        "Swedish": "SE",
        "Swiss": "CH",
        "Syrian": "SY",
        "Taiwanese": "SY",
        "Tajik": "TJ",
        "Tanzanian": "TJ",
        "Thai": "TH",
        "Timorese": "TH",
        "Togolese": "TG",
        "Tokelauan": "TK",
        "Tongan": "TO",
        "Trinidadian / Tobagonian": "TT",
        "Tunisian": "TN",
        "Turkish": "TR",
        "Turkmen": "TM",
        "Turks and Caicos Islands": "TM",
        "Tuvaluan": "TV",
        "Ugandan": "UG",
        "Ukrainian": "UA",
        "Uruguayan": "UY",
        "Uzbekistani": "UZ",
        "Vatican City": "VU",
        "Venezuelan": "VU",
        "Vietnamese": "VN",
        "Virgin Islands (British)": "VG",
        "Virgin Islands (U.S.)": "VI",
        "Wake Island (U.S.)": "VI",
        "Wallisian / Futunan": "WF",
        "Western Saharan": "EH",
        "Yemenite": "YE",
        "Zambian": "ZM",
        "Zimbabwean": "ZW"
    }


    const key = {
        'American': 'us',
        'British': 'gb',
        'Polish': 'pl',
        'Chinese': 'cn',
        'Portuguese': 'pt',
        'Ukrainian': 'ua',
        'German': 'de',
        'South African': 'za',
        'Spanish': 'es',
        'Moldovan': 'md',
        'Malaysian': 'my',
        'Zimbabwean': 'zw',
        'Jamaican': 'jm',
        'Danish': 'dk',
        'Sri Lankan': 'lk',
        'Mauritanian': 'mr',
        'Angolan': 'ao',
        'Irish': 'ie',
        'Mexican': 'mx',
        'Moroccan': 'ma',
        'Bulgarian': 'bg',
        'Lithuanian': 'lt',
        'Swedish': 'se',
        'Japanese': 'jp',
        'Estonian': 'ee',
        'Nigerian': 'ng',
        'Honduran': 'hn',
    }


    let isoCode =
        countryCodes[nationality] ? countryCodes[nationality] :
        String(nationality).substr(0, 2)

    isoCode = String(isoCode).toLowerCase()

    return `https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.5.0/flags/4x3/${isoCode}.svg`
}